---
ci:
  autoupdate_schedule: quarterly
  skip: ["golangci-lint-full"]  # just for now

repos:
  - repo: meta
    hooks:
      - id: identity

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.0.2
    hooks:
      - id: golangci-lint-full
