---
services:

  mysql:
    image: mysql
    container_name: MySQL
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports: ["3306:3306"]

  ecom-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecom-app:latest
    container_name: EComApp
    restart: on-failure
    ports: ["8080:8080"]
    depends_on: ["mysql"]
