# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
---
networks:
  e-commerce:

services:
  datastore:
    image: postgres:17
    container_name: PostgreSQL
    command: ["postgres", "-c", "log_statement=all"]
    ports: ["5432:5432"]
    networks: ["e-commerce"]
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  backend:
    build: { context: ".", dockerfile: "docker/Dockerfile" }
    image: ecom-app
    container_name: EComApp
    restart: on-failure
    ports: ["8080:8080"]
    networks: ["e-commerce"]
    depends_on: ["datastore"]

  backend-migrations:
    command: docker/entrypoint-migrations.sh
    image: ecom-app
    container_name: Migrations
    restart: on-failure
    networks: ["e-commerce"]
    depends_on: ["datastore"]
